//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCEN_ROLES
    {
        public LCEN_ROLES()
        {
            this.LCEN_USERS = new HashSet<LCEN_USERS>();
        }
    
        public decimal ROLE_ID { get; set; }
        public string DESCR { get; set; }
    
        public virtual ICollection<LCEN_USERS> LCEN_USERS { get; set; }
    }
}
