//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCEN_HOURS
    {
        public LCEN_HOURS()
        {
            this.LCEN_TEAM1 = new HashSet<LCEN_TEAM1>();
        }
    
        public decimal HOUR_ID { get; set; }
        public string HRNUM { get; set; }
        public string HRDISP { get; set; }
        public Nullable<decimal> SHIFT { get; set; }
    
        public virtual LCEN_SHIFTS LCEN_SHIFTS { get; set; }
        public virtual ICollection<LCEN_TEAM1> LCEN_TEAM1 { get; set; }
    }
}
