//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCEN_USERS
    {
        public LCEN_USERS()
        {
            this.LCEN_TEAM1 = new HashSet<LCEN_TEAM1>();
            this.LCEN_TEAM11 = new HashSet<LCEN_TEAM1>();
        }
    
        public string USERID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FULL_NAME { get; set; }
        public string USER_EMAIL { get; set; }
        public Nullable<decimal> USER_ROLE { get; set; }
        public string STATUS { get; set; }
    
        public virtual LCEN_ROLES LCEN_ROLES { get; set; }
        public virtual ICollection<LCEN_TEAM1> LCEN_TEAM1 { get; set; }
        public virtual ICollection<LCEN_TEAM1> LCEN_TEAM11 { get; set; }
    }
}
