//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCEN_TEAM1
    {
        public decimal ID { get; set; }
        public System.DateTime EFFDT { get; set; }
        public Nullable<decimal> HOUR { get; set; }
        public Nullable<decimal> SHIFT { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDT { get; set; }
        public string EDITEDBY { get; set; }
        public Nullable<System.DateTime> EDITEDDT { get; set; }
        public Nullable<decimal> CELL1 { get; set; }
        public Nullable<decimal> CELL2 { get; set; }
        public Nullable<decimal> CELL3 { get; set; }
        public Nullable<decimal> CELL4 { get; set; }
        public Nullable<decimal> CELL6 { get; set; }
        public Nullable<decimal> CELL7 { get; set; }
    
        public virtual LCEN_HOURS LCEN_HOURS { get; set; }
        public virtual LCEN_SHIFTS LCEN_SHIFTS { get; set; }
        public virtual LCEN_USERS LCEN_USERS { get; set; }
        public virtual LCEN_USERS LCEN_USERS1 { get; set; }
    }
}
