//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCEN_SHIFTS
    {
        public LCEN_SHIFTS()
        {
            this.LCEN_HOURS = new HashSet<LCEN_HOURS>();
            this.LCEN_TEAM1 = new HashSet<LCEN_TEAM1>();
        }
    
        public decimal SHIFT_ID { get; set; }
        public string SHIFTNUM { get; set; }
        public string SHIFTDISP { get; set; }
    
        public virtual ICollection<LCEN_HOURS> LCEN_HOURS { get; set; }
        public virtual ICollection<LCEN_TEAM1> LCEN_TEAM1 { get; set; }
    }
}
